parameters:
    locale: 'en'
    app_locales: en|pl

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $locales: '%app_locales%'
            $defaultLocale: '%locale%'
    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests,Kernel.php}'
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
    gedmo.listener.translatable:
        class: Gedmo\Translatable\TranslatableListener
        tags:
          name: doctrine.event_subscriber
          connection: default
        calls:
          - [setAnnotationReader, ['@annotation_reader']]
          - [setTranslatableLocale, ["@=service('request_stack').getCurrentRequest() ? service('request_stack').getCurrentRequest().getLocale() : 'en'"]]
          - [setTranslationFallback, [true]]
