parameters:
    locale: 'en'
    app_locales: en|pl

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $locales: '%app_locales%'
            $defaultLocale: '%locale%'
    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests,Kernel.php}'
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
